name: AutoDownloader
on:
  workflow_dispatch: # 手动触发
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: python3 Install
      run: |
        sudo apt install python3 -y
        sudo apt install python3-dev -y
        sudo apt install python3-pip -y
    - name: 拉取源码和安装依赖
      run: |
        cd ~/
        git clone -b main https://github.com/winkxx/epic-awesome-gamer
        cd ~/epic-awesome-gamer
        pip3 install -r requirements.txt
        cd ~/epic-awesome-gamer/sr

    - name: 安装
      run: |
        cd ~/epic-awesome-gamer/src
        python3 main.py install       
        #cd ~/epic-awesome-gamer/src
        #python3 main.py install
