name: AutoDownloader
on:
  workflow_dispatch: # 手动触发
jobs:
  AutoDownloaderProcess:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: python3 Install
      run: |
        apt-get update
        apt-get install sudo
        sudo apt install python3 -y
        sudo apt install python3-dev -y
        sudo apt install python3-pip -y
    - name: 拉取源码和安装依赖
      run: |
        git clone -b main https://github.com/luminoleon/epicgames-claimer.git
        cd epicgames-claimer
        pip3 install -r requirements.txt
        sudo sh install_dependencies.sh
    - name: 运行
      run: |
        python3 main.py -u ${{ secrets.EPIC_USER }} -p ${{ secrets.EPIC_PAS }} -ptt ${{ secrets.TG_BOT }} -pti ${{ secrets.TG_ID }}

